### ISSUE TITLE
toml file variables

### ISSUE THREAD

**Issue by Tekunogosu** [violet4/vsdlib#4]
Have a distinction of what a variable is throughout the toml

```toml
[colors]
pink="#ff12ee"

[c2.r1]
text="Landing\n Gear"
key="h"
color="{pink}"
color="$pink"
```
